server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://notification-db:3306/notification_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          ssl:
            enable: ${MAIL_SSL_ENABLE:true}
          starttls:
            enable: false


resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      notificationService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

logging:
  level:
    com.founderlink.notification: DEBUG

# RabbitMQ queues
rabbitmq:
  exchange: founderlink.exchange
  queue:
    startup: notification.startup.queue
    investment: notification.investment.queue
    team: notification.team.queue
    messaging: notification.messaging.queue
    team-accepted: notification.team.accepted.queue
    team-rejected: notification.team.rejected.queue
    payment-completed: notification.payment.completed.queue
    payment-failed: notification.payment.failed.queue
    investment-approved: notification.investment.approved.queue
    investment-rejected: notification.investment.rejected.queue
    user-registered: user-registered-queue
    email-verification: email-verification-queue
