server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://user-db:3306/user_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

internal:
  secret: ${INTERNAL_SECRET}

logging:
  level:
    com.founderlink.user: DEBUG
