server:
  port: 8091

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://wallet-db:3306/wallet_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

logging:
  level:
    com.founderlink.wallet: DEBUG
